### PR TITLE
Revert 121 el pp refund

### PR DESCRIPTION
**Pull request by Jankyboy**
#168

### CODE REVIEW

**Review by roopakv — CHANGES_REQUESTED** [review]
thank you opening this PR. however this is huge! not possible to review easily and you seem to be reverting commits that did the right thing? also i think this has breaking changes.

please open an issue discussing what you are trying to do. Let us discuss and then get it in piece by piece

**Comment by roopakv** [comment]
@Jankyboy i'm closing this PR. please open an issue first.

**Comment by Jankyboy** [comment]
Igazság szerint most teljesen elvesztem ebben a PR-ben. Kérem segítséged illetve javaslatod egy kisebb rövidebb összeállításban ami helyes is az enyémmel ellentétben

**Comment by Michelle9979** [comment]
Thanks

**Review by Michelle9979 — APPROVED** [review]

**Pull request closed without merging**
