### PR TITLE
change type of Item.Amount from string to int to get it working with …

### PR DESCRIPTION
**Pull request by bejonwe**
…the newest PayPal API

Sadly I didn't find any source for this change, but I discovered the problem today while developing with this SDK.

### CODE REVIEW

**Comment by bejonwe** [comment]
Strange, according to the docs it should be of type string: https://developer.paypal.com/docs/api/payments/#definition-item

But I definitely get a number as response at least when using the sandbox.

**Comment by plutov** [comment]
So I will keep it as string?

**Comment by bejonwe** [comment]
These are example responses from the PayPal sandbox and live API:
[response_sandbox.txt](https://github.com/logpacker/PayPal-Go-SDK/files/757044/response_sandbox.txt)
[response_live.txt](https://github.com/logpacker/PayPal-Go-SDK/files/757045/response_live.txt)

As you can see the quantity is returned as number. That's why I have to use my fix, else I get an error (obviously): "json: cannot unmarshal number into Go value of type string"

This is definitely a problem of PayPal, but at the moment you can't use this library (at least when you need items) without this change.

**Comment by plutov** [comment]
Thanks for the investigation @bejonwe

**Pull request merged**
